package frc.robot.subsystems;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Subsystem;

import frc.robot.Ports;


//Activates the piston to shoot the ball into the shooter 
public class ShooterPusher extends Subsystem {
	
	static final int WAIT_MS = 1000;
	
    DoubleSolenoid upDown;
    
    public enum Position {
		UP, // The piston is in the up position and shoots the ball
		DOWN, // The piston is in the down position and can recieve another ball
		UNKNOWN;
	}

	public ShooterPusher() {
		// the double solenoid valve will send compressed air from the tank wherever needed
		upDown = new DoubleSolenoid(Ports.CAN.PCM, Ports.PCM.HOOK_UP, Ports.PCM.HOOK_DOWN); // make sure ports are properly sets in Ports.java	
	}
	
	@Override
	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here0
	}

	@Override
	public void periodic() {
		// Put code here to be run every loop

	}

	public void setPosition(Position pos) //Telling the piston to be in the selected position 
	{
		switch(pos)
		{
			case UP: //Telling the solenoid to have the piston go up
			{
				upDown.set(DoubleSolenoid.Value.kReverse); // adjust direction if needed
				break;
			}
			case DOWN: //Telling the solenoid to have the piston go up
			{
				upDown.set(DoubleSolenoid.Value.kForward); // adjust direction if needed
				break;
			}
			default:
			{
				// do nothing
			}
		}
	}

	public Position getPosition() //Getting the current position
	{
		DoubleSolenoid.Value value = upDown.get();
		
		switch(value)
		{
			case kReverse: //Checking if the piston is in the kReverse position (up)
			{
				return Position.UP;
			}
			case kForward: //Checking if the piston is in the kFoward position (down)
			{
				return Position.DOWN;
			}
			default: //position unknown
			{
				return Position.UNKNOWN;
			}
		}
	}
}